---
server: 
  http2: 
    enabled: true
spring: 
  application: 
    name: rmt-gql
# These are graphql settings    
graphql:
 tools:
# The files ending with .graphqls are treated as schema files  
  schema-location-pattern: "**/*.graphqls"
 servlet:
  exception-handlers-enabled: true
  maxQueryDepth: 5
  tracing-enabled: true
  actuator-metrics: true
# The voyager is for browsing our schema files
# enabled: false for production build  
 voyager:
  enabled: false     
# The playground is used to test the application by sending the graphl queries
# enabled: false for production build  
 playground:
  enabled: true
  headers:
   Authorization: My Secret Token
  tabs:
   - name: Get Customer
     query: classpath:playground/customer.graphql
     variables: classpath:playground/customer_variables.json
   - name: Add Card Account
     query: classpath:playground/add_card_account.graphql
     variables: classpath:playground/add_card_account_variables.json
   - name: Sample Get Bank Account
     query: classpath:playground/bank_account.graphql
     variables: classpath:playground/bank_account_variables.json
...